baseURL = "GNDEC-Ldh.github.io"
languageCode = "en-us"
title = "GNDEC-Ldh"
theme = "serif"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/gne.jpg"
    desktop = "images/logo/gne.jpg"
    desktop_height = "36px"
    alt = "GNDEC_Ldh"

  [params.homepage_meta_tags]
    meta_description = "Oldest Engineering College of Punjab, up-lifting rural population"
    meta_og_title = "GNDEC-Ldh"
    meta_og_type = "Institute"
    meta_og_url = "https://gndec.ac.in/"
    meta_og_image = ""
    meta_og_description = "Oldest Engineering College ... "
    meta_twitter_card = "summary"
    meta_twitter_site = "@xyz"
    meta_twitter_creator = "@xys"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Up-lifting rural masses through technical education'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Courses"
    url = "/services/"
      weight = 1

  [[menu.main]]
      name = "People"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
